sudo: false
os:
  - osx
  - linux

language: node_js
node_js:
    - '8'
dist: trusty

before_install:
    - if [ $TRAVIS_OS_NAME == "linux" ]; then
        export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
        sh -e /etc/init.d/xvfb start;
        sleep 3;
      fi
install: |
      ./.travis/install.sh
script: |
      ./.travis/script.sh
deploy:
     provider: script
     script: ./.travis/deploy.sh
     skip_cleanup: true
     on:
       all_branches: true
cache: false

notifications:
  webhooks:
    urls:
      - https://chat.hyperledger.org/hooks/BG3PeSerMSWRDSceE/GPCnCSqxMoyfqaTvLePSGudWjoCBwAcCT6bAKYRjK2sKSCM9
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
